function [dphi1,dphi2,dphi3] = find_Ds_Velocity(dth1,dth2,dth3,l_Arm,phi1,phi2,phi3,th1,th2,th3)
%FIND_DS_VELOCITY
%    [DPHI1,DPHI2,DPHI3] = FIND_DS_VELOCITY(DTH1,DTH2,DTH3,L_ARM,PHI1,PHI2,PHI3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-May-2021 14:06:41

t2 = cos(phi1);
t3 = cos(phi2);
t4 = cos(phi3);
t5 = cos(th1);
t6 = cos(th2);
t7 = cos(th3);
t8 = sin(phi1);
t9 = sin(phi2);
t10 = sin(phi3);
t11 = sin(th1);
t12 = sin(th2);
t13 = sin(th3);
t14 = dth1.*l_Arm.*t11;
t15 = dth2.*l_Arm.*t12;
t16 = dth3.*l_Arm.*t13;
t17 = dth1.*l_Arm.*t2.*t5;
t18 = dth2.*l_Arm.*t3.*t6;
t19 = dth3.*l_Arm.*t4.*t7;
t20 = dth1.*l_Arm.*t5.*t8;
t21 = dth2.*l_Arm.*t6.*t9;
t22 = dth3.*l_Arm.*t7.*t10;
t23 = t14+t15+t16;
t24 = t20+t21+t22;
t25 = t17+t18+t19;
t26 = sign(t25);
t27 = sign(t24);
t28 = -t26;
t29 = -t27;
t30 = t23.*Inf+t28.*Inf+t29.*Inf;
dphi1 = t30;
if nargout > 1
    dphi2 = t30;
end
if nargout > 2
    dphi3 = t30;
end
