function [dth3,dphi2,dphi3] = find_Ds_Velocity(dphi1,dth1,dth2,l_Arm,phi1,phi2,phi3,th1,th2,th3)
%FIND_DS_VELOCITY
%    [DTH3,DPHI2,DPHI3] = FIND_DS_VELOCITY(DPHI1,DTH1,DTH2,L_ARM,PHI1,PHI2,PHI3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-May-2021 13:47:14

t2 = cos(phi1);
t3 = cos(phi2);
t4 = cos(phi3);
t5 = cos(th1);
t6 = cos(th2);
t7 = cos(th3);
t8 = sin(phi1);
t9 = sin(phi2);
t10 = sin(phi3);
t11 = sin(th1);
t12 = sin(th2);
t13 = sin(th3);
t14 = t13.^2;
t15 = dth1.*l_Arm.*t11;
t16 = dth2.*l_Arm.*t12;
t17 = dth1.*l_Arm.*t2.*t5;
t18 = dth2.*l_Arm.*t3.*t6;
t19 = dphi1.*l_Arm.*t2.*t11;
t20 = dth1.*l_Arm.*t5.*t8;
t21 = dth2.*l_Arm.*t6.*t9;
t22 = dphi1.*l_Arm.*t8.*t11;
t23 = l_Arm.*t3.*t10.*t12;
t24 = l_Arm.*t4.*t9.*t12;
t25 = l_Arm.*t3.*t10.*t13;
t26 = l_Arm.*t4.*t9.*t13;
t27 = -t22;
t28 = -t24;
t29 = -t26;
t30 = t15+t16;
dth3 = -t30./(l_Arm.*t13);
if nargout > 1
    t33 = t19+t20+t21;
    t31 = t23+t28;
    t32 = t25+t29;
    t36 = t17+t18+t27;
    t34 = 1.0./t31;
    dphi2 = -t4.*t34.*t36-t10.*t33.*t34+(t30.*(t4.^2.*t7+t7.*t10.^2))./(t13.*t23+t13.*t28);
end
if nargout > 2
    t35 = 1.0./t32;
    dphi3 = -(t30.*(t3.*t4.*t7+t7.*t9.*t10))./(l_Arm.*t3.*t10.*t14-l_Arm.*t4.*t9.*t14)+t3.*t35.*t36+t9.*t33.*t35;
end
