function ddth1 = find_Triangle_Ddth1(g,l_Arm,m1,m2,tau1,tau2,tau3,th1)
%FIND_TRIANGLE_DDTH1
%    DDTH1 = FIND_TRIANGLE_DDTH1(G,L_ARM,M1,M2,TAU1,TAU2,TAU3,TH1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-May-2021 17:46:25

t2 = cos(th1);
ddth1 = (1.0./l_Arm.^2.*(tau1.*2.0+tau2.*2.0+tau3.*2.0-g.*l_Arm.*m1.*t2.*2.0-g.*l_Arm.*m2.*t2+sqrt(3.0).*g.*l_Arm.*m2.*sin(th1)))./(m1.*2.0+m2.*2.0);
