function [ddth1,ddth2,ddth3] = find_Dds_Triangle_2D_Force(dth1,dth2,dth3,g,l_Arm,m1,m2,tau1,tau2,tau3,th1,th2,th3)
%FIND_DDS_TRIANGLE_2D_FORCE
%    [DDTH1,DDTH2,DDTH3] = FIND_DDS_TRIANGLE_2D_FORCE(DTH1,DTH2,DTH3,G,L_ARM,M1,M2,TAU1,TAU2,TAU3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-May-2021 22:10:43

t2 = cos(th1);
t3 = cos(th2);
t4 = cos(th3);
t5 = dth1.^2;
t6 = dth2.^2;
t7 = dth3.^2;
t8 = l_Arm.^2;
t9 = th1.*2.0;
t10 = th2.*2.0;
t11 = th3.*2.0;
t14 = -th2;
t16 = -th3;
t12 = 1.0./t8;
t13 = -t9;
t15 = -t10;
t17 = -t11;
t18 = t14+th1;
t19 = t16+th1;
t20 = t16+th2;
t32 = t9+t14;
t21 = t17+th2;
t22 = cos(t18);
t23 = cos(t19);
t24 = cos(t20);
t26 = sin(t18);
t27 = sin(t19);
t28 = sin(t20);
t30 = t15+th1+th3;
t31 = t13+th2+th3;
t33 = t9+t15;
t34 = t10+t17;
t39 = cos(t32);
t44 = t11+t15+th1;
t25 = cos(t21);
t29 = t21+th1;
t36 = cos(t30);
t37 = cos(t31);
t38 = sin(t30);
t40 = cos(t33);
t41 = cos(t34);
t42 = sin(t33);
t43 = sin(t34);
t45 = t33+th3;
t46 = cos(t44);
t35 = cos(t29);
t47 = cos(t45);
t48 = m2.*t40;
t49 = m1.*t41;
t50 = -t48;
t51 = -t49;
t52 = m1+m2+t50+t51;
t53 = 1.0./t52;
ddth1 = t12.*t53.*(tau1.*-2.0+t22.*tau2.*2.0+t23.*tau3.*2.0-t35.*tau2.*2.0-t36.*tau3.*2.0+t41.*tau1.*2.0+g.*l_Arm.*m1.*t2.*2.0+g.*l_Arm.*m2.*t2-g.*l_Arm.*m1.*t46-g.*l_Arm.*m2.*t46+m2.*t6.*t8.*t26.*4.0+m2.*t7.*t8.*t27.*2.0+m2.*t7.*t8.*t38.*2.0+m2.*t5.*t8.*t42.*2.0-g.*l_Arm.*m2.*cos(t15+th1)+g.*l_Arm.*m2.*cos(t17+th1)-g.*l_Arm.*m1.*cos(t34+th1)).*(-1.0./2.0);
if nargout > 1
    ddth2 = t12.*t53.*(tau2.*-2.0+t22.*tau1.*2.0+t24.*tau3.*2.0-t35.*tau1.*2.0-t37.*tau3.*2.0+tau2.*cos(t9+t17).*2.0-g.*l_Arm.*m1.*t3+g.*l_Arm.*m2.*t3+g.*l_Arm.*m1.*t25+g.*l_Arm.*m2.*t25-g.*l_Arm.*m1.*t39-g.*l_Arm.*m2.*t39-m1.*t5.*t8.*t26.*2.0-m2.*t5.*t8.*t26.*4.0+m1.*t7.*t8.*t28.*4.0+m2.*t7.*t8.*t28.*2.0+m1.*t6.*t8.*t43.*2.0-m2.*t6.*t8.*t42.*2.0+g.*l_Arm.*m1.*cos(t9+t21)+m1.*t5.*t8.*sin(t29).*2.0+m2.*t7.*t8.*sin(t31).*2.0-g.*l_Arm.*m2.*cos(t11+t13+th2)).*(-1.0./2.0);
end
if nargout > 2
    ddth3 = (t12.*t53.*(tau3.*2.0-t23.*tau1.*2.0-t24.*tau2.*2.0+t36.*tau1.*2.0+t37.*tau2.*2.0-t40.*tau3.*2.0+g.*l_Arm.*m1.*t4+g.*l_Arm.*m2.*t4.*2.0-g.*l_Arm.*m1.*t47-g.*l_Arm.*m2.*t47+m1.*t5.*t8.*t27.*2.0+m1.*t6.*t8.*t28.*4.0-m1.*t5.*t8.*t38.*2.0+m1.*t7.*t8.*t43.*2.0+g.*l_Arm.*m1.*cos(t9+t16)-g.*l_Arm.*m1.*cos(t10+t16)-g.*l_Arm.*m2.*cos(t10+t13+th3)))./2.0;
end
