function [th2,th3] = find_Triangle_Th2_Th3(th1)
%FIND_TRIANGLE_TH2_TH3
%    [TH2,TH3] = FIND_TRIANGLE_TH2_TH3(TH1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-May-2021 17:46:25

t2 = pi.*(2.0./3.0);
th2 = t2+th1;
if nargout > 1
    th3 = -t2+th1;
end
