function l_Hand = find_L_Hand(alpha_Body,beta_Body,gamma_Body,hand_Length,l_Alpha_Hand,l_Beta_Hand,offset_Body,width_Body)
%FIND_L_HAND
%    L_HAND = FIND_L_HAND(ALPHA_BODY,BETA_BODY,GAMMA_BODY,HAND_LENGTH,L_ALPHA_HAND,L_BETA_HAND,OFFSET_BODY,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Jun-2021 19:16:04

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = cos(l_Alpha_Hand);
t6 = cos(l_Beta_Hand);
t7 = sin(alpha_Body);
t8 = sin(beta_Body);
t9 = sin(gamma_Body);
t10 = sin(l_Alpha_Hand);
t11 = sin(l_Beta_Hand);
t12 = width_Body./2.0;
t13 = hand_Length.*t5.*t11;
t14 = -t13;
t15 = t12+t14;
l_Hand = [-t3.*t4.*t15+hand_Length.*t5.*t6.*t9-hand_Length.*t4.*t8.*t10,-t15.*(t7.*t8+t2.*t3.*t9)+offset_Body.*t2+hand_Length.*t10.*(t3.*t7-t2.*t8.*t9)-hand_Length.*t2.*t4.*t5.*t6,t15.*(t2.*t8-t3.*t7.*t9)+offset_Body.*t7-hand_Length.*t10.*(t2.*t3+t7.*t8.*t9)-hand_Length.*t4.*t5.*t6.*t7];
