function r_Hand = find_R_Hand(alpha_Body,beta_Body,gamma_Body,hand_Length,offset_Body,r_Alpha_Hand,r_Beta_Hand,width_Body)
%FIND_R_HAND
%    R_HAND = FIND_R_HAND(ALPHA_BODY,BETA_BODY,GAMMA_BODY,HAND_LENGTH,OFFSET_BODY,R_ALPHA_HAND,R_BETA_HAND,WIDTH_BODY)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    01-Jun-2021 19:16:03

t2 = cos(alpha_Body);
t3 = cos(beta_Body);
t4 = cos(gamma_Body);
t5 = sin(alpha_Body);
t6 = cos(r_Alpha_Hand);
t7 = cos(r_Beta_Hand);
t8 = sin(beta_Body);
t9 = sin(gamma_Body);
t10 = sin(r_Alpha_Hand);
t11 = sin(r_Beta_Hand);
t12 = width_Body./2.0;
t13 = hand_Length.*t6.*t11;
t14 = t12+t13;
r_Hand = [t3.*t4.*t14-hand_Length.*t4.*t8.*t10+hand_Length.*t6.*t7.*t9,t14.*(t5.*t8+t2.*t3.*t9)+offset_Body.*t2+hand_Length.*t10.*(t3.*t5-t2.*t8.*t9)-hand_Length.*t2.*t4.*t6.*t7,-t14.*(t2.*t8-t3.*t5.*t9)+offset_Body.*t5-hand_Length.*t10.*(t2.*t3+t5.*t8.*t9)-hand_Length.*t4.*t5.*t6.*t7];
